# Generated by Django 4.2.9 on 2024-04-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_follow_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow_pair',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
    ]
