# Generated by Django 4.2.9 on 2024-04-28 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_follow_unique_follow_pair_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='PostLike',
        ),
        migrations.AlterModelTable(
            name='postlike',
            table='post_like',
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'comment_like',
            },
        ),
    ]
